### ISSUE TITLE
Authentication token is getting expired - Jenkins (Bayesian)

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-analytics/fabric8-analytics-jenkins-plugin#2]
Referencing the existing issue here to make it more relevant.

https://github.com/openshiftio/openshift.io/issues/186

**Comment by sbose78** [comment]
The offline token had expired.
Alexey has shared a new token with  Srikrishna.

**Comment by maxandersen** [comment]
What is the status here ? Is this fixed ?

**Comment by arunkumars08** [comment]
@maxandersen The issue is fixed now. Authentication is working fine now and you can see the stack reports link appearing in the pipelines section.

PFA for your reference,
<img width="1920" alt="screen shot 2017-06-02 at 11 36 37 am" src="https://cloud.githubusercontent.com/assets/7880465/26713020/ef7c8a92-4787-11e7-8a09-91bfd1485634.png">
<img width="1920" alt="screen shot 2017-06-02 at 11 36 26 am" src="https://cloud.githubusercontent.com/assets/7880465/26713027/f38ff34e-4787-11e7-938f-8a6dee112a81.png">
